#!/bin/bash

src=$(pwd)
export PYTHONPATH=$src

# firewall settings
sudo iptables -A OUTPUT -p tcp --tcp-flags RST RST -j DROP

# turn off checksum offloading
sudo ethtool -K eth0 gro off

# run main program
sudo python -O $src"/main.py" "$@"
